adminUser:
  password: vault:spritebristle/adminUser:password
  username: admin
dashboardUrl: https://dashboard.play-jxaas.live
enableDocker: false
pipelineUser:
  email: arcalos-admin@googlegroups.com
  token: vault:spritebristle/pipelineUser:token
  username: cloudbees-ci-cd-play[bot]
prow:
  hmacToken: vault:spritebristle/prow:hmacToken
segmentWriteKey: vault:spritebristle:segmentWriteKey
